site_name: COM-Server

repo_url: https://github.com/jonyboi396825/COM-Server
edit_uri: ""

nav:
  - Home: "index.md"
  - Known issues: "issues.md"
  - "User Guide":
    - "Getting Started": "guide/getting-started.md"
    - "Library API": "guide/library-api.md"
    - "Custom IO Thread": "guide/custom-io-thread.md"
  - "Server API": 
    - "Server Overview": "server/index.md"
    - "Version 1": "server/v1.md"
    - "Version 0": "server/v0.md"
  
theme:
  name: readthedocs
  highlightjs: true
  locale: en

plugins:
- search
- mkdocstrings