# Runs pytest when something is pushed to develop or if there is a pull request to master.

name: Run Pytest on develop 

# Controls when the workflow will run
on:
  # trigger when PR to master or push to develop
  pull_request:
    branches: [ master ]
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt && pip3 install -e .
      
      - name: Run pytest and then test the version greater test
        run: |
          pytest -vv
          pytest tests/_test_version_greater.py -vv
