name: Tests
on:
  push:
    branches:
      - develop
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches:
      - develop
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  
  workflow_dispatch:

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Linux, python: '3.10', os: ubuntu-latest, tox: passive}
          - {name: Windows, python: '3.10', os: windows-latest, tox: passive}
          - {name: Mac, python: '3.10', os: macos-latest, tox: passive}
          - {name: '3.9', python: '3.9', os: ubuntu-latest, tox: passive}
          - {name: '3.8', python: '3.8', os: ubuntu-latest, tox: passive}
          - {name: '3.7', python: '3.7', os: ubuntu-latest, tox: passive}
          - {name: '3.6', python: '3.6', os: ubuntu-latest, tox: passive}
          - {name: Typing, python: '3.10', os: ubuntu-latest, tox: typing}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - run: pip install tox
      - run: tox -e ${{ matrix.tox }}